---
- name: '{{ ansible_name_module }} | Import Create additional CA CM tasks'
  import_tasks: create-additional-ca-cm.yml
  vars:
    ca_bundle_cm_name: '{{ registry_ca_bundle_cm_name }}'
    ca_trust_stores: '{{ registries_trust_stores }}'

- name: '{{ ansible_name_module }} | update registry config'
  command: >
    {{ openshift_cli }} patch image.config.openshift.io cluster --type=merge -p '{"spec": {"additionalTrustedCA": {"name": "{{ ca_cm_name }}" }}}'
  when:
    - ca_bundle_cm_created is defined
    - ca_bundle_cm_created | bool
  register: registry_additional_ca_added

